apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-apache
  template:
    metadata:
      labels:
        app: sensor-apache
    spec:
      containers:
      - name: sensor-apache
        image: msermpezis/sensor-apache:latest
        ports:
        - containerPort: 80