apiVersion: v1
kind: Service
metadata:
  name: sensor-apache-service
spec:
  selector:
    app: sensor-apache
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.1.183